package com.glider;

import com.glider.snake.SnakeGame;
import com.glider.util.ConsoleGame;

public class Main {
    public static void main(String[] args) {
        ConsoleGame game = new SnakeGame();
        game.loop();
    }

    /*
    ..........
    .+........
    .*........
    ./........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
    ..........
     */
}
